### ISSUE TITLE
Reset captcha when re-trying upload after fail

### ISSUE THREAD

**Issue by jarrilla** [jarrilla/demo-uploader#2]
When re-trying upload after fail, need to reset captcha. otherwise another attempt can't be submitted without reloading page

**Comment by jarrilla** [comment]
Resetting form also does not reset captcha

**Comment by tariq-shuvo** [comment]
solved

**Comment by tariq-shuvo** [comment]
This issue is fixed in this new commit 6b96e371002b3c8c3b29f860fea2976d22096257
